#!/command/with-contenv sh
# shellcheck shell=bash

echo "Running db migration script";
if [ "${USE_JEMALLOC:-false}" = "true" ]; then
    export LD_PRELOAD=/usr/local/lib/libjemalloc.so
fi
exec node /db_migrations/index.js;
